# Generated by Django 4.0.4 on 2022-12-01 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gift',
            old_name='name',
            new_name='gift_name',
        ),
    ]
